import type { Metadata } from "next";
import { inter, playfair_display } from "@/lib/fonts";
import "@/styles/globals.css";
import { Footer, Header } from "@/components";

export const metadata: Metadata = {
  title: "Landing Córdoba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${inter.variable} ${playfair_display.variable}`}
    >
      <body className={"antialiased"}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
